### ISSUE TITLE
FAQ Needs to be updated.

### ISSUE THREAD

**Issue by galactic-beyond** [interlock-network/interlock-whitepaper#10]
### Bug description

FAQ in this repo needs to match the FAQ in Coda, somewhat.

### Expected behavior

Merge the copy that is living in Coda from the Website FAQ that was added.

### Anything else?

Keep blockchain related questions that are in the old FAQ in GitHub.

**Comment by Treevuhh** [comment]
Completed entering the needed copy and fixed format for easier navigation; and added the FAQ to the README.
