### ISSUE TITLE
Fix bad links in github.io whitepaper instance

### ISSUE THREAD

**Issue by blairmunroakusa** [interlock-network/interlock-whitepaper#12]
whitepaper on github.io (copy linked from main website) contains two broken links

1) bad markdown image embed under the #Tokenomics section
2) bad link to company website at bottom of whitepaper

**Comment by Treevuhh** [comment]
1. @justerhan anyway to temporarily fix the token flow image under the #Tokenomics section in ReType until the WP is permanently moved over to VitePress? It seems to only appear on the ReType page, the image looks fine through Github. 
Or I can just switch out the url link on the website to our github file for the WP for now? Thoughts?

2. Fixed the bad company link in the WP for now. 

The permanent solution will be when Erhan is done with ReType and has the WP deployed through VitePress.

**Comment by justerhan** [comment]
Should be fixed, if not, please reopen.
