### ISSUE TITLE
Update favicon and logos 

### ISSUE THREAD

**Issue by Treevuhh** [interlock-network/interlock-whitepaper#6]
Needs updated to the new logo. Assigned to last to update.

**Comment by championshuttler** [comment]
Where its not updated yet?

**Comment by championshuttler** [comment]
got it https://interlock-network.github.io/interlock-whitepaper/whitepaper/

**Comment by Treevuhh** [comment]
https://github.com/interlock-network/interlock-whitepaper/blob/master/favicon.ico
